# Generated by Django 2.2.5 on 2019-09-27 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='acc',
            name='events_registered',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='acc',
            name='karma',
            field=models.IntegerField(default=0),
        ),
    ]
