# Generated by Django 2.2.1 on 2019-09-13 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190913_1755'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='idd',
            field=models.IntegerField(default=0),
        ),
    ]
