# Generated by Django 2.2.1 on 2019-09-13 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_idd'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='idd',
        ),
    ]
