# Generated by Django 2.2.1 on 2019-09-16 07:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_remove_post_idd'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='beginning_at',
            field=models.DateTimeField(default=datetime.date(1970, 1, 1)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='ending_at',
            field=models.DateTimeField(default=datetime.date(1970, 1, 1)),
            preserve_default=False,
        ),
    ]
