# Generated by Django 2.2.1 on 2019-09-18 07:37

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20190918_0916'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='nachname',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, unique=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='urlVK',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='vorname',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
