# Generated by Django 2.2.1 on 2019-09-20 15:19

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20190918_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='events_registered',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, size=None),
        ),
    ]
