# Generated by Django 2.2.1 on 2019-09-20 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20190920_1819'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='users_registered',
            field=models.CharField(blank=True, max_length=10000),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='events_registered',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
