# Generated by Django 2.2.1 on 2019-09-23 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20190920_1828'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='min_karma',
            field=models.IntegerField(default=0),
        ),
    ]
