# Generated by Django 2.2.1 on 2019-09-27 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_post_min_karma'),
    ]

    operations = [
        migrations.CreateModel(
            name='KarmaChange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idd', models.IntegerField()),
                ('vorname', models.CharField(blank=True, max_length=20)),
                ('nachname', models.CharField(blank=True, max_length=50)),
                ('ball', models.IntegerField()),
                ('code', models.IntegerField()),
                ('comment', models.CharField(max_length=100)),
            ],
        ),
    ]
