# Generated by Django 2.2.1 on 2019-09-27 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_karmachange'),
    ]

    operations = [
        migrations.DeleteModel(
            name='KarmaChange',
        ),
    ]
