# Generated by Django 2.2.1 on 2019-09-27 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_delete_karmachange'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='slug',
            field=models.SlugField(default='default', max_length=200, unique=True),
            preserve_default=False,
        ),
    ]
