# Generated by Django 2.2.1 on 2019-09-27 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_userprofile_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='slug',
        ),
    ]
