# Generated by Django 2.2.1 on 2019-09-27 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_auto_20190927_2215'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='extended_profile',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
