# Generated by Django 2.2.1 on 2019-09-27 20:08

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_userprofile_extended_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='extended_profile',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None),
        ),
    ]
