# Generated by Django 2.2.1 on 2019-09-28 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0023_userprofile_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='profile_image',
        ),
    ]
