# Generated by Django 2.2.1 on 2019-09-28 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0025_auto_20190928_0958'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='karma_counts',
            field=models.IntegerField(default=5),
        ),
    ]
