# Generated by Django 2.2.1 on 2019-09-28 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0026_userprofile_karma_counts'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='additional_skills',
            field=models.TextField(blank=True, default='Не заполнено', max_length=500),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='allergy',
            field=models.TextField(blank=True, default='Не заполнено', max_length=500),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='children_exp',
            field=models.TextField(blank=True, default='Не заполнено', max_length=500),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='expectations',
            field=models.TextField(blank=True, default='Не заполнено', max_length=500),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='foreigns_lang',
            field=models.TextField(blank=True, default='Не заполнено', max_length=500),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='specialization',
            field=models.TextField(blank=True, default='Не заполнено', max_length=500),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='volonteer_exp',
            field=models.TextField(blank=True, default='Не заполнено', max_length=500),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='work_place',
            field=models.TextField(blank=True, default='Не заполнено', max_length=500),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='Согласие',
            field=models.BooleanField(default=False),
        ),
    ]
