# Generated by Django 2.2.1 on 2019-09-28 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0027_auto_20190928_1140'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='Согласие',
        ),
    ]
