# Generated by Django 2.2.1 on 2019-09-28 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0029_museum_museummember'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='min_karma',
            field=models.FloatField(default=0),
        ),
    ]
