# Generated by Django 2.2.1 on 2019-09-28 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0031_post_reg_ending_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='museummember',
            name='museum',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
