# Generated by Django 2.2.1 on 2019-09-28 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0032_museummember_museum'),
    ]

    operations = [
        migrations.AddField(
            model_name='museum',
            name='slug',
            field=models.SlugField(default='djangodbmodelsfieldscharfield', max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='museum',
            name='description',
            field=models.TextField(blank=True, default='Не заполнено', max_length=1200),
        ),
        migrations.AlterField(
            model_name='museum',
            name='image',
            field=models.ImageField(default='images/no-img.jpg', upload_to='images'),
        ),
    ]
