# Generated by Django 2.2.1 on 2019-09-28 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0033_auto_20190928_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profile_image',
            field=models.ImageField(default='images/no-img.jpg', upload_to='images'),
        ),
        migrations.AlterField(
            model_name='museum',
            name='slug',
            field=models.SlugField(max_length=200, unique=True),
        ),
    ]
