# Generated by Django 2.2.1 on 2019-09-28 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0034_auto_20190928_1717'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='museums',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='museums',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
