# Generated by Django 2.2.1 on 2019-09-28 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0036_auto_20190928_2101'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='images/no-img.jpg', upload_to='images'),
        ),
    ]
