# Generated by Django 2.2.1 on 2019-09-28 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0037_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='card_id',
            field=models.CharField(default='AA1234', max_length=6),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='images/event-no-image.png', upload_to='images'),
        ),
    ]
