# Generated by Django 2.2.1 on 2019-09-29 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0040_post_karma_reward'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='forschung_points',
            field=models.IntegerField(default=0),
        ),
    ]
